<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <Title>Blazorify Bootstrap</Title>
    <Description>A powerful Blazor component library that seamlessly integrates Bootstrap's responsive design and styling capabilities with the simplicity and efficiency of Blazor.</Description>
    <PackageTags>blazor; bootstrap;</PackageTags>
    <PackageProjectUrl>https://github.com/blazorify/bootstrap</PackageProjectUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <RepositoryUrl>https://github.com/blazorify/bootstrap</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <Version>1.0.0</Version>
    <Authors>lambidu</Authors>
    <Company>Blazorify</Company>
    <Configurations>Debug;Release</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <PropertyGroup>
    <NoWarn>1701;1702;IDE0058</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LibSassHost" Version="1.5.0" />
    <PackageReference Include="LibSassHost.Native.linux-x64" Version="1.5.0" />
    <PackageReference Include="LibSassHost.Native.osx-x64" Version="1.5.0" />
    <PackageReference Include="LibSassHost.Native.win-arm" Version="1.5.0" />
    <PackageReference Include="LibSassHost.Native.win-arm64" Version="1.5.0" />
    <PackageReference Include="LibSassHost.Native.win-x64" Version="1.5.0" />
    <PackageReference Include="LibSassHost.Native.win-x86" Version="1.5.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components" Version="9.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="9.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.ViewFeatures" Version="2.2.0" />
    <PackageReference Include="Microsoft.JSInterop" Version="9.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="System.Net.Http" Version="4.3.4" />
    <PackageReference Include="System.Security.Cryptography.Xml" Version="9.0.0" />
    <PackageReference Include="System.Text.Encodings.Web" Version="9.0.0" />
    <PackageReference Include="System.Text.RegularExpressions" Version="4.3.1" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources/bootstrap/**/*.scss" />
    <EmbeddedResource Include="Resources/Scripts/**/*.js" />
    <EmbeddedResource Include="Resources/index.scss" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\LICENSE">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <None Update="LICENSE">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>

    <None Update="README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
